version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: star-watch-app:dev
    container_name: star-watch-app-dev
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app
    networks:
      - star-watch-network
    ports:
      - 3000:3000
volumes:
  star-watch-db-data:
    name: star-watch-db-data
networks:
  star-watch-network:
    name: star-watch-network
